version: "3.9"

services:

  possim:
    build: .
    volumes:
      - ./eth_possim:/opt/privatenet/eth_possim:ro
      - ./Tiltfile:/opt/privatenet/Tiltfile:ro
      - ./Makefile:/opt/privatenet/Makefile:ro
      - ./.data:/opt/privatenet/.data:rw
      - ./tests:/opt/privatenet/tests
      - ./requirements-dev.txt:/opt/privatenet/requirements-dev.txt
      - ./pbs_config.yaml:/opt/privatenet/pbs_config.yaml
    ports:
      # execution wsrpc
      - "18546:18546"
      # execution rpc
      - "18544:18544"
      # beacon rest
      - "15050:15050"
      # beacon teku
      - "15051:15051"
      # beacon lighthouse
      - "15151:15151"
      # mev relay
      - "38000:38000"
    command: freshrun
